This section documents breaking changes between Micronaut GraphQL versions:

=== Micronaut GraphQL 5.0.0

- The Apollo Websocket protocol (subscriptions-transport-ws) classes and configuration deprecated previously have all been removed. Refer to the version 4.0.0 breaking changes notes for details.

- The Controller class api:configuration.graphql.GraphiQLController[] was previously instantiated with the deprecated `GraphQLApolloWsConfiguration` type. That is changed to `GraphQLConfiguration`.

=== Micronaut GraphQL 4.0.0

The Apollo Websocket protocol (subscriptions-transport-ws) classes and configuration have been refactored  and deprecated to pave the way for a newer websocket protocol (graphql-ws). The subscriptions-transport-ws protocol will be removed in a future version and client code should be migrated to use the new protocol. To continue using the subscriptions-transport-ws protocol, the following must be considered when upgrading:

- The configuration prefix for subscriptions-transport-ws is changed from `graphql-ws` to `graphql-apollo-ws`
- The implementation classes for subscriptions-transport-ws have moved from the `io.micronaut.configuration.graphql.ws` package to `io.micronaut.configuration.graphql.ws.apollo`. The implementation for the newer protocol has taken their place in `io.micronaut.configuration.graphql.ws`
- The implementation classes for subscriptions-transport-ws have been renamed from `GraphQLWs*` to `GraphQLApolloWs*`. For example, `GraphQLWsConfiguration` is now `GraphQLApolloWsConfiguration`.
