To use the Micronaut GraphQL integration you must have the `micronaut-graphql` dependency on your classpath:

.build.gradle
[source,groovy,subs="attributes"]
----
compile "io.micronaut.graphql:micronaut-graphql:{version}"
----

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.micronaut.graphql</groupId>
    <artifactId>micronaut-graphql</artifactId>
    <version>{version}</version>
</dependency>
----

The `micronaut-graphql` module transitively includes the `graphql-java` dependency and provides a Micronaut `GraphQLController`
which enables query execution via HTTP.

As outlined in https://graphql.org/learn/serving-over-http the following HTTP requests are supported:

* `GET` request with `query`, `operationName` and `variables` query parameters. The `variables` query parameter must be json encoded.
* `POST` request with `application/json` body and keys `query` (String), `operationName` (String) and `variables` (Map).

Both produce a `application/json` response.

You only must define a bean of type `graphql.GraphQL` containing the GraphQL schema and runtime wiring.

The `graphql.GraphQL` bean can be defined by just using the https://github.com/graphql-java/graphql-java[GraphQL Java] implementation,
or in combination with other integration libraries like https://github.com/graphql-java-kickstart/graphql-java-tools[GraphQL Java Tools]
and https://github.com/leangen/graphql-spqr[GraphQL SPQR].
There are various https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples[examples] provided in the repository.
