Micronaut supports https://graphql.org[GraphQL] via the `micronaut-graphql` module.

=== Release History

=== 1.2.0

* Provide user defined `DataLoaderRegistry` bean to `ExecutionInput` in `DefaultGraphQLInvocation`
  (https://github.com/micronaut-projects/micronaut-graphql/issues/10[#10]).
  This change requires Micronaut `1.2.0`.
* Upgrade to GraphiQL `0.13.2` and made GraphiQL version configurable (https://github.com/micronaut-projects/micronaut-graphql/issues/11[#11]).

=== 1.1.0

* Upgrade to GraphQL Java `13.0`.

=== 1.0.2

* Fixed content type resolution (https://github.com/micronaut-projects/micronaut-graphql/issues/7[#7]).

=== 1.0.1

* Fixed loading GraphiQL configuration (https://github.com/micronaut-projects/micronaut-graphql/issues/6[#6]).

==== 1.0.0

* Removed the `GraphQLContextBuilder` and `GraphQLRootBuilder` in favour of a more generic `GraphQLExecutionInputCustomizer` capable of
  transforming the `ExecutionInput` before execution.

==== 1.0.0.RC2

* Upgrade to GraphQL Java `12.0`.
* Introduced a `GraphQLJsonSerializer` interface and default `JacksonGraphQLJsonSerializer` implementation capable of providing a customized
  Jackson `ObjectMapper`, or plugging in a completely different JSON serializer/deserializer library.

==== 1.0.0.RC1

* Initial release.
