Create your application via the Command Line tool:

[source]
----
mn create-app helloworld --features=graphql
----

If you already have an application, add the micronaut graphql dependency:

dependency:micronaut-graphql[groupId="io.micronaut.graphql"]

Configure the `/graphql` endpoint by adding to `application.yml`:

[source,yaml]
----
graphql:
  enabled: true
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: true
----

And then in the `resources` folder, create a file named `schema.graphqls`.
This file will contain the definition of your GraphQL schema.
In our case, it will contain the following:

[source,graphql]
----
type Query {
    hello(name: String): String!
}
----

Create a DataFetcher for the `hello` query:

snippet::io.micronaut.graphql.docs.HelloDataFetcher[tags="imports,clazz", project-base="docs-examples/hello-world"]

And then create the GraphQL bean:

snippet::io.micronaut.graphql.docs.GraphQLFactory[tags="imports,clazz", project-base="docs-examples/hello-world"]

You should be all set.
Start your application by running `./gradlew run`, open your browser to your http://localhost:8080/graphiql[local graphiql], and you should be able to run the following queries:

Query without params:

[source,graphql]
----
query {
    hello
}
----

Returns:

[source,json]
----
{
  "data": {
    "hello": "Hello World!"
  }
}
----

Query with params:

[source,graphql]
----
query {
    hello(name: "Micronaut")
}
----

Returns:

[source,json]
----
{
  "data": {
    "hello": "Hello Micronaut!"
  }
}
----
