plugins {
    id("io.micronaut.application")
}

micronaut {
    importMicronautPlatform = false
    runtime("netty")
    testRuntime("junit5")
}

configurations.configureEach {
    resolutionStrategy {
        preferProjectModules()
    }
}

dependencies {
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}
