plugins {
    id "com.gradleup.shadow"
    id "io.micronaut.application"
    id 'io.micronaut.build.internal.graphql-base'
}

group "io.micronaut.example"
version project.projectVersion

dependencies {
    compileOnly libs.graal.svm

    implementation projects.micronautGraphql
    implementation mn.micronaut.http.client
    implementation mn.micronaut.jackson.databind
    implementation mn.micronaut.runtime

    testImplementation mnTest.micronaut.test.junit5
    runtimeOnly mnLogging.logback.classic
    runtimeOnly mn.snakeyaml

    testRuntimeOnly mnTest.junit.jupiter.engine
    testRuntimeOnly mnTest.junit.platform.launcher
    testRuntimeOnly mn.snakeyaml
}

application {
    mainClass = "example.Application"
}

micronaut {
    version.set(libs.versions.micronaut.platform.get())
    coreVersion.set(libs.versions.micronaut.asProvider().get())
    runtime("netty")
}

tasks.named("test") {
    useJUnitPlatform()
}
