plugins {
    id "io.micronaut.build.internal.parent"
}

repositories {
    mavenCentral()
}

configurations.configureEach {
    resolutionStrategy {
        preferProjectModules()
    }
}

project(":test-suite-graal") {
    if (System.getenv("SONAR_TOKEN") != null) {
        sonar {
            skipProject = true
        }
    }
}
