The `micronaut-graphql` module comes bundled with support for GraphQL over web sockets
(https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md).

GraphQL over web sockets must be explicitly enabled via the `graphql.graphql-apollo-ws.enabled` application property.
While the server is capable of handling the queries and mutations also over web sockets it might not be supported in all clients.
Some clients have a way of configuring a different endpoint for subscriptions and/or some filter to only use the websocket for subscriptions.

The following configuration properties can be set:

.src/main/resources/application.yml
[source,yaml]
----
graphql:
  graphql-apollo-ws:
    enabled: false // <1>
    path: /graphql-ws // <2>
    keep-alive-enabled: true // <3>
    keep-alive-interval: 15s // <4>
----
<1> Enables/disables GraphQL over web sockets. Default `false`.
<2> Configures the GraphQLApolloWs endpoint path. Default `/graphql-ws`.
<3> Enables/disables keep alive, this might be needed to prevent clients reconnecting. Default `true`.
<4> Configures the keep alive interval, specific clients might need different values, or it could be set higher to reduce some load `15s`.

There is an example present https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/chat[chat], that features a very basic chat application.
For real applications the subscriptions are usually based on some pub/sub solution.
An example using subscriptions with kafka can be found here, https://github.com/openweb-nl/kafka-graphql-examples/tree/ge-micronaut/graphql-endpoint[graphql-endpoint using micronaut].


