The `micronaut-graphql` module comes bundled with support for GraphQL over web sockets.

Support is provided for the graphql-ws protocol
(https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md).

GraphQL over web sockets via the current graphql-ws protocol must be explicitly enabled via the `graphql.graphql-ws.enabled` application property.

The following configuration properties can be set for the graphql-ws support:

.src/main/resources/application.yml
[source,yaml]
----
graphql:
  graphql-ws:
    enabled: false // <1>
    path: /graphql-ws // <2>
    connection-init-wait-timeout: 5s // <3>
----
<1> Enables/disables the graphql-ws implementation of GraphQL over web sockets. Default `false`.
<2> Configures the graphql-ws endpoint path. Default `/graphql-ws`.
<3> Configures the maximum time allowed for a client to initiate a graphql-ws connection after the WebSocket is initially opened. Default `15s`.

There is an example present https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/chat[chat], that features a very basic chat application.
For real applications the subscriptions are usually based on some pub/sub solution.
An example using subscriptions with kafka can be found here, https://github.com/openweb-nl/kafka-graphql-examples/tree/ge-micronaut/graphql-endpoint[graphql-endpoint using micronaut].


