The `micronaut-graphql` module comes bundled with support for GraphQL over web sockets
(https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md).

GraphQL over web sockets must be explicitly enabled via the `graphql.graphql-ws.enabled` application property.
While the server is capable of handling the queries and mutations also over web sockets it might not be supported in all clients.
Some clients have a way of configuring a different endpoint for subscriptions and/or some filter to only use the websocket for subscriptions.

The following configuration properties can be set:

.src/main/resources/application configuration
[configuration]
----
graphql:
  graphql-ws:
    enabled: false
    path: /graphql-ws
    keep-alive-enabled: true
    keep-alive-interval: 15s
----
- `enabled` enables/disables GraphQL over web sockets. Default `false`.
- `path` configures the GraphQLWs endpoint path. Default `/graphql-ws`.
- `keep-alive-enabled` enables/disables keep alive, this might be needed to prevent clients reconnecting. Default `true`.
- `keep-alive-interval` configures the keep alive interval, specific clients might need different values, or it could be set higher to reduce some load `15s`.

There is an example present https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/chat[chat], that features a very basic chat application.
For real applications the subscriptions are usually based on some pub/sub solution.
An example using subscriptions with kafka can be found here, https://github.com/openweb-nl/kafka-graphql-examples/tree/ge-micronaut/graphql-endpoint[graphql-endpoint using micronaut].


