plugins {
    id("micronaut-graphql.docs-examples-conventions")
    id "groovy"
}

micronaut {
    testRuntime "spock"
    version.set(libs.versions.micronaut.platform.get())
    coreVersion.set(libs.versions.micronaut.asProvider().get())
}

dependencies {
    implementation mn.groovy
    testImplementation mn.micronaut.http.client
    implementation(mnSerde.micronaut.serde.jackson)
}

application {
    mainClass = "io.micronaut.graphql.docs.Application"
}

//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-M7-groovy-5.0")
    }
}
