plugins {
    id("micronaut-graphql.docs-examples-conventions")
    id "groovy"
}

micronaut {
    version.set(libs.versions.micronaut.platform.get())
    coreVersion.set(libs.versions.micronaut.asProvider().get())
}

dependencies {
    implementation mn.groovy
    testImplementation mn.micronaut.http.client
    testImplementation(mnTest.micronaut.test.spock)
    testRuntimeOnly(mnTest.junit.platform.suite)
    implementation(mnSerde.micronaut.serde.jackson)
}

application {
    mainClass = "io.micronaut.graphql.docs.Application"
}

tasks.withType(Test) {
    useJUnitPlatform()
}
